spring.application.name=FAMPortfolioManager




spring.datasource.url=jdbc:mysql://localhost:3306/portfoliomanager
spring.datasource.username=root
spring.datasource.password=n3u3da!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.h2.console.enabled=true

server.port=8080

alphavantage.api.key=L4RRUAIUM7R4YNYB
alphavantage.base.url=https://www.alphavantage.co/query