spring.application.name=FAMPortfolioManager

spring.datasource.url=jdbc:h2:mem:cddb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.h2.console.enabled=true

server.port=8080


# Alpha Vantage API configuration
alphavantage.api.key=YOUR_KEY
alphavantage.base.url=https://www.alphavantage.co/query

# Cache is configured programmatically via CacheConfig.java (CaffeineCacheManager bean)