package com.training.FAMPortfolioManager.model;

// Asset - JPA entity representing a single investment asset
// Annotate with @Entity and @Table(name = "assets")
// RELATIONSHIPS:
//   @ManyToOne(fetch = FetchType.LAZY) - relationship to Portfolio
//   @JoinColumn(name = "portfolio_id", nullable = false)
//   private Portfolio portfolio; // Back-reference to owning portfolio
//
// Fields: // done 
//   id (Long) - @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
//   ticker (String) - stock/crypto ticker symbol
//   companyName (String) - name of the asset issuer
//   quantity (double) - number of units held
//   purchasePrice (double) - price per unit at purchase
//   purchaseDate (LocalDateTime) - when asset was purchased

// IMPORTS NEEDED:
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.persistence.Id;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.FetchType;
import java.time.LocalDateTime;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;


// This entity class represents an individual asset within a portfolio. 
// Each asset is linked to a portfolio and contains details about the investment.
@Entity
@Table(name = "assets")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Asset {

    // The @Id annotation marks this field as the primary key
    // @GeneratedValue indicates that its value will be automatically generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String companyName;
    private LocalDateTime datePurchased;
    private String ticker;
    private double quantity;
    private double purchasePrice;

    // Many-to-one relationship with Portfolio. Each asset belongs to one portfolio.
    // The @JoinColumn annotation specifies the foreign key column in the "assets" table that references the "portfolios" table.
    // FetchType.LAZY means that the portfolio data will only be loaded from the database when it is accessed.
    // The "nullable = false" attribute ensures that every asset must be associated with a portfolio.
    // This field allows us to navigate from an asset back to its owning portfolio, which is important for calculating portfolio-level metrics and for API responses that include asset details.
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "portfolio_id", nullable = false)
    private Portfolio portfolio;

    // Constructor 
    public Asset(String companyName, LocalDateTime datePurchased, String ticker, double quantity, double purchasePrice) {
        this.companyName = companyName;
        this.datePurchased = datePurchased;
        this.ticker = ticker;
        this.quantity = quantity;
        this.purchasePrice = purchasePrice;
    }

}
